### ISSUE TITLE
Gradient-path draws a line to the starting position as if the path is finished with "z", even if it is not

### ISSUE THREAD

**Issue by nathggns** [cereallarceny/gradient-path#13]
Using gradient-path on an svg with an "unfinished path" (i.e, it does not "end" with a `z`) results in gradient-path drawing a line to the end position even though the original SVG does not contain one. Interestingly, circles stop where they should but paths do not.

**[CodeSandbox](https://codesandbox.io/s/gradient-path-not-finished-4dr04?file=/src/index.js:42-525)**

**To Reproduce**

Use gradient-path on an svg that does not end at the beginning, such as the following. 

```html
<svg id="gradient-path" width="300" height="200" viewBox="0 0 100 100">
      <path
        fill="none"
        d="M24.3,30
                C11.4,30,5,43.3,5,50
                s6.4,20,19.3,20
                c19.3,0,32.1-40,51.4-40
                C88.6,30,95,43.3,95,50
                s-6.4,20-19.3,20"
      ></path>
    </svg>
```

```js

const gp = new GradientPath({
  path: document.querySelector("#gradient-path path"),
  segments: 30,
  samples: 3,
  precision: 2 // Optional
});

gp.render({
  type: "path",
  fill: [
    { color: "#C6FFDD", pos: 0 },
    { color: "#FBD786", pos: 0.25 },
    { color: "#F7797D", pos: 0.5 },
    { color: "#6DD5ED", pos: 0.75 },
    { color: "#C6FFDD", pos: 1 }
  ],
  width: 10
});

gp.render({
  type: "circle",
  fill: "#eee",
  width: 3,
  stroke: "#444",
  strokeWidth: 0.5
});
```

**Expected behavior**

The path should end where the SVG does.

**Screenshots**

![image](https://user-images.githubusercontent.com/719814/101378758-66c9db00-38ab-11eb-84c8-dcd11d6abc82.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 87

**Comment by kasparsiricenko** [comment]
Same:
![image](https://user-images.githubusercontent.com/64709398/102413046-064e4280-3ffd-11eb-8b32-642abe697402.png)

**Comment by TheSonOfThomp** [comment]
Any workarounds for this?

**Comment by weepy** [comment]
yeah i get this issue too

**Comment by cereallarceny** [comment]
@nathggns Do we just need to add `z` on to the end of the path string? Is that all that's required to fix this?

**Comment by nathggns** [comment]
No. The issue is that the path is interpreted as though it has a z at the end (I.e, draw a line to the end), even if it doesn't. This means a line gets drawn that shouldn't. This can make it difficult if not impossible to use gradient path on paths that don't end where they start.

**Comment by cereallarceny** [comment]
Understood. Is there an obvious solution to this? Would you be willing to write a PR I could merge?

If I had to guess, we could maybe have a flag that designates when a path should complete itself or not: `completePath: true` or something like that.

**Comment by nathggns** [comment]
I've not had time to look into this personally.

**Comment by nathggns** [comment]
I'd argue the library should work out if the SVG has a close path command or not, and not close the path if it doesn't. It does claim to support any SVG path after all.

**Comment by CreativeSau** [comment]
I've stumbled upon this library yesterday and have been experiencing the same issue. I've launched an attempt at fixing the open paths issue and submitted a PR #31 

It's been successfully tested with a custom path, and the demo path, it might require some additional testing though. Feel free to test [the built version of the fork](https://github.com/CreativeSau/gradient-path/blob/CreativeSau-openPath-patch-1/dist/index.js).

**Comment by cereallarceny** [comment]
Hey @CreativeSau , thanks for the PR! Took a look and I can merge if you check out my comment first. I don't want to include the `dist` directory in our repo. That's bad practice.

**Comment by CreativeSau** [comment]
I was hoping for some feedback from the users in this issue, @cereallarceny . The `dist` directory has been removed.

**Comment by cereallarceny** [comment]
@CreativeSau  @nathggns This should hopefully be fixed by the following release: https://github.com/cereallarceny/gradient-path/releases/tag/v2.3.0

Closing for now, let me know if this release doesn't work for you.
